# Generated by Django 5.1.7 on 2026-03-04 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid_agencia",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="CID Agência"
                    ),
                ),
                (
                    "agencia_original",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nome original da agência",
                    ),
                ),
                ("agencia", models.CharField(max_length=50, verbose_name="Agência")),
                (
                    "grupo",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Grupo"
                    ),
                ),
                (
                    "matricula_gg",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Matrícula Gerente Geral do mês anterior ao da folha",
                    ),
                ),
                (
                    "inativada",
                    models.BooleanField(default=False, verbose_name="Inativada"),
                ),
                (
                    "inatualizavel",
                    models.BooleanField(
                        default=False, verbose_name="Não atualizar automaticamente"
                    ),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Observações"
                    ),
                ),
                (
                    "atualizada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Atualizada em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agência / Unidade",
                "ordering": ["cid_agencia"],
            },
        ),
        migrations.CreateModel(
            name="Agrupamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agrupamento",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Agrupamento"
                    ),
                ),
                (
                    "inativado",
                    models.BooleanField(default=False, verbose_name="Inativado"),
                ),
                (
                    "ordem_apresentacao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ordem de Apresentação"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Física"), ("J", "Jurídica")],
                        max_length=1,
                        null=True,
                        verbose_name="Tipo de Pessoa",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        verbose_name="CPF / CNPJ",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=60, null=True, verbose_name="Nome"),
                ),
                (
                    "nome_social",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Nome Social"
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=80, verbose_name="Email"),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="Observações"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contratado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[("F", "Física"), ("J", "Jurídica")],
                        max_length=1,
                        verbose_name="Tipo de Pessoa",
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        max_length=14, unique=True, verbose_name="CPF / CNPJ"
                    ),
                ),
                (
                    "contratado",
                    models.CharField(max_length=60, verbose_name="Contratado"),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Matrícula"
                    ),
                ),
                (
                    "numero_dependente",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nº Dependentes"
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=80, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Banco"
                    ),
                ),
                (
                    "agencia",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "conta_corrente",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Conta Corrente",
                    ),
                ),
                (
                    "celebrado_em",
                    models.DateField(
                        blank=True, null=True, verbose_name="Celebrado em"
                    ),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Observações"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seguradora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod_seguradora",
                    models.CharField(
                        max_length=4,
                        null=True,
                        unique=True,
                        verbose_name="Cód. Seguradora",
                    ),
                ),
                (
                    "seguradora",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Seguradora"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=14, verbose_name="CNPJ"),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="Observações"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Superintendencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid_superintendencia",
                    models.CharField(
                        max_length=4,
                        null=True,
                        unique=True,
                        verbose_name="CID Superintendência",
                    ),
                ),
                (
                    "superintendencia",
                    models.CharField(
                        max_length=10, null=True, unique=True, verbose_name="Sigla"
                    ),
                ),
                (
                    "nome_descritivo",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome Completo"
                    ),
                ),
                (
                    "matricula_superintendente",
                    models.CharField(
                        max_length=20, verbose_name="Matrícula Superintendente"
                    ),
                ),
                (
                    "inativada_em",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inativada em"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
            ],
            options={
                "verbose_name": "Superintendência",
                "ordering": ["cid_superintendencia"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Observações"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Matrícula"
                    ),
                ),
                (
                    "colaborador",
                    models.CharField(
                        max_length=150, verbose_name="Nome do Colaborador"
                    ),
                ),
                (
                    "nome_social",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nome Social",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "funcao",
                    models.IntegerField(blank=True, null=True, verbose_name="Função"),
                ),
                (
                    "suspenso",
                    models.BooleanField(default=False, verbose_name="Suspenso"),
                ),
                (
                    "impedido",
                    models.BooleanField(default=False, verbose_name="Impedido"),
                ),
                ("inativo", models.BooleanField(default=False, verbose_name="Inativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agencia",
                        verbose_name="Agência (CID)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "produto",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Produto"
                    ),
                ),
                (
                    "inativado_em",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inativado em"
                    ),
                ),
                (
                    "divulgacao_ativa",
                    models.BooleanField(default=False, verbose_name="Divulgação Ativa"),
                ),
                (
                    "prioridade_divulgacao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Prioridade de Divulgação"
                    ),
                ),
                (
                    "mes_referencia_producao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Mês Referência Produção"
                    ),
                ),
                (
                    "mes_referencia_folha_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Mês Ref. Folha Pagamento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "agrupamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agrupamento",
                        verbose_name="Agrupamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetaMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes_referencia",
                    models.DateField(verbose_name="Mês/Ano de Referência"),
                ),
                (
                    "meta",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Valor da Meta"
                    ),
                ),
                (
                    "percentual_fechado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% Fechado",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "agencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.agencia",
                        verbose_name="Agência",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta Mensal",
                "verbose_name_plural": "Metas Mensais",
            },
        ),
        migrations.CreateModel(
            name="Ramo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod_grupo",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Cód. Grupo"
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Grupo"
                    ),
                ),
                (
                    "cod_ramo",
                    models.IntegerField(
                        null=True, unique=True, verbose_name="Cód. Ramo"
                    ),
                ),
                (
                    "ramo",
                    models.CharField(
                        max_length=150, null=True, unique=True, verbose_name="Ramo"
                    ),
                ),
                (
                    "grupo_e_ramo",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Grupo e Ramo",
                    ),
                ),
                ("inativo", models.BooleanField(default=False, verbose_name="Inativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.produto",
                        verbose_name="Produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apolice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[("BANSEG", "Banseg"), ("OUTRAS", "Outras Cias")],
                        default="BANSEG",
                        max_length=15,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "tipo_negocio",
                    models.CharField(
                        choices=[
                            ("NOVO", "Negócio Novo"),
                            ("RENOVACAO", "Renovação"),
                            ("ENDOSSO", "Endosso"),
                        ],
                        default="NOVO",
                        max_length=15,
                        verbose_name="Tipo de Negócio",
                    ),
                ),
                (
                    "mod",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Mod"
                    ),
                ),
                (
                    "contrato",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Contrato"
                    ),
                ),
                (
                    "item",
                    models.IntegerField(blank=True, null=True, verbose_name="Item"),
                ),
                (
                    "dt_venc",
                    models.DateField(blank=True, null=True, verbose_name="Dt Venc."),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "sexo",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="Sexo"
                    ),
                ),
                (
                    "cid",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CID"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="Tipo Pessoa"
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True, max_length=18, null=True, verbose_name="CPF/CNPJ"
                    ),
                ),
                (
                    "ordem",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Ordem"
                    ),
                ),
                (
                    "ramo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ramo",
                        verbose_name="Ramo",
                    ),
                ),
                (
                    "seg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.seguradora",
                        verbose_name="Seguradora",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agencia",
            name="superintendencia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.superintendencia",
                verbose_name="Superintendência",
            ),
        ),
    ]
