# Generated by Django 6.0.7 on 2026-08-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='atendimento_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Em atendimento desde'),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='atendimento_por',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Em atendimento por'),
        ),
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão (%)'),
        ),
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='seguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seguradora', verbose_name='Seguradora'),
        ),
    ]
