# Generated by Django 5.1.7 on 2026-03-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apolice",
            name="premio_liquido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Prêmio Líquido",
            ),
        ),
        migrations.AddField(
            model_name="apolice",
            name="seguradora_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apolices_destino",
                to="core.seguradora",
                verbose_name="Seguradora Destino",
            ),
        ),
        migrations.AddField(
            model_name="apolice",
            name="tipo_documento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.tipodocumento",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddField(
            model_name="apolice",
            name="usuario",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Usuário"
            ),
        ),
        migrations.AlterField(
            model_name="apolice",
            name="cid",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Unidade/CID"
            ),
        ),
        migrations.AlterField(
            model_name="apolice",
            name="contrato",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Contrato/Documento"
            ),
        ),
        migrations.AlterField(
            model_name="apolice",
            name="dt_venc",
            field=models.DateField(
                blank=True, null=True, verbose_name="Dt Venc. / Fim Vigência"
            ),
        ),
        migrations.AlterField(
            model_name="apolice",
            name="nome",
            field=models.CharField(max_length=150, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="apolice",
            name="seg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apolices_origem",
                to="core.seguradora",
                verbose_name="Seguradora",
            ),
        ),
    ]
