# Generated by Django 6.0.7 on 2026-08-10 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_indicacao_atendimento_em_indicacao_atendimento_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='responsavel_demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_responsavel', to='core.colaborador', verbose_name='Responsável pela demanda'),
        ),
    ]
