# Generated by Django 5.1.7 on 2026-03-17 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_apolice_premio_liquido_apolice_seguradora_destino_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apolice",
            name="agrupamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.agrupamento",
                verbose_name="Agrupamento",
            ),
        ),
    ]
