# Generated by Django 5.1.7 on 2026-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_apolice_agrupamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="inativado_em",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="mes_referencia_folha_pagamento",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="mes_referencia_producao",
        ),
        migrations.AddField(
            model_name="produto",
            name="cod_ppo_rateio",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Cód. PPO Rateio"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="cod_ppo_volume",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Cód. PPO Volume"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="inativado",
            field=models.BooleanField(default=False, verbose_name="Inativado"),
        ),
        migrations.AddField(
            model_name="produto",
            name="mes_folha_pagamento_em_aberto",
            field=models.DateField(
                blank=True, null=True, verbose_name="Mês Folha Pgto em Aberto"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="mes_producao_em_aberto",
            field=models.DateField(
                blank=True, null=True, verbose_name="Mês Produção em Aberto"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="verba_folha",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Verba Folha"
            ),
        ),
    ]
