# Generated by Django 6.0.7 on 2026-08-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_indicacao_responsavel_demanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrizacaoBaseNovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_sistema', models.CharField(max_length=100, unique=True)),
                ('coluna_excel', models.CharField(blank=True, max_length=150, null=True)),
                ('valor_fixo', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ligacaoindicacao',
            name='motivo_nao_venda',
            field=models.CharField(blank=True, choices=[('Condições comerciais (preço)', 'Condições comerciais (preço)'), ('Condições financeiras', 'Condições financeiras'), ('Condições técnicas', 'Condições técnicas'), ('Desistiu', 'Desistiu'), ('Efetivou com o corretor atual', 'Efetivou com o corretor atual'), ('Falta de retorno do cliente/indicador', 'Falta de retorno do cliente/indicador'), ('Mal atendimento Seguradora', 'Mal atendimento Seguradora'), ('Operação Empréstimo', 'Operação Empréstimo'), ('Venda do bem', 'Venda do bem')], max_length=50, null=True, verbose_name='Motivo Não Venda'),
        ),
    ]
