# Generated by Django 5.1.7 on 2026-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_produto_inativado_em_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="verba_folha",
        ),
        migrations.AddField(
            model_name="produto",
            name="verba_credito_folha",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Verba de Crédito para a folha",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="verba_estorno_folha",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Verba de estorno para a folha",
            ),
        ),
    ]
