# Generated by Django 6.0.6 on 2026-08-20 21:45
#
# Esvaziada em 2026-08-26: essas mesmas 5 remoções + o alter de
# origem_informacao já existem, com os mesmos nomes de campo, na linha de
# migrations 0006_alter_indicacao_origem_informacao ->
# 0007_remove_indicacao_chave_unica -> 0008_remove_indicacao_numero_contrato_and_more
# (histórico paralelo que chegou depois via merge do git). Mantém o nome do
# arquivo (para não quebrar bancos que já marcaram esta migration como
# aplicada), só que sem operações duplicadas.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_prod_vendas_emissao'),
    ]

    operations = []
