# Generated by Django 6.0.6 on 2026-08-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_prod_vendas_emissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='chave_unica',
        ),
        migrations.RemoveField(
            model_name='indicacao',
            name='numero_contrato',
        ),
        migrations.RemoveField(
            model_name='indicacao',
            name='numero_endosso',
        ),
        migrations.RemoveField(
            model_name='indicacao',
            name='seguradora',
        ),
        migrations.RemoveField(
            model_name='indicacao',
            name='tipo_documento',
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='origem_informacao',
            field=models.CharField(blank=True, choices=[('WhatsApp', 'WhatsApp'), ('Planilha da internet', 'Planilha da internet'), ('Telefone', 'Telefone'), ('E-mail', 'E-mail')], max_length=30, null=True, verbose_name='Origem da informação'),
        ),
    ]
