# Generated by Django 5.1.7 on 2026-03-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_produto_verba_folha_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaborador",
            name="agencia",
        ),
        migrations.RemoveField(
            model_name="metamensal",
            name="agencia",
        ),
        migrations.RenameField(
            model_name="contratado",
            old_name="agencia",
            new_name="unidade",
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid_unidade",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="CID Unidade"
                    ),
                ),
                (
                    "unidade_original",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nome original da unidade",
                    ),
                ),
                ("unidade", models.CharField(max_length=50, verbose_name="Unidade")),
                (
                    "grupo",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Grupo"
                    ),
                ),
                (
                    "matricula_gg",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Matrícula Gerente Geral do mês anterior ao da folha",
                    ),
                ),
                (
                    "matricula_superintendente",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Matrícula do Superintendente",
                    ),
                ),
                (
                    "inativada",
                    models.BooleanField(default=False, verbose_name="Inativada"),
                ),
                (
                    "inatualizavel",
                    models.BooleanField(
                        default=False, verbose_name="Não atualizar automaticamente"
                    ),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Observações"
                    ),
                ),
                (
                    "atualizada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Atualizada em"
                    ),
                ),
                (
                    "superintendencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.superintendencia",
                        verbose_name="Superintendência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
                "ordering": ["cid_unidade"],
            },
        ),
        migrations.AddField(
            model_name="colaborador",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.unidade",
                verbose_name="Unidade (CID)",
            ),
        ),
        migrations.AddField(
            model_name="metamensal",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.unidade",
                verbose_name="Unidade",
            ),
        ),
        migrations.DeleteModel(
            name="Agencia",
        ),
    ]
