# Generated by Django 6.0.7 on 2026-08-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_indicacao_origem_informacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='chave_unica',
        ),
    ]
