# Generated by Django 6.0.6 on 2026-08-20 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_indicacao_chave_unica_and_more'),
        ('core', '0008_remove_indicacao_numero_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAnbima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True, verbose_name='UF')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('uf_estado', models.CharField(blank=True, max_length=60, verbose_name='UF - Estado')),
                ('ordem_apresentacao', models.IntegerField(default=0, verbose_name='Ordem de Apresentação')),
            ],
            options={
                'verbose_name': 'Estado (ANBIMA)',
                'verbose_name_plural': 'Estados (ANBIMA)',
                'ordering': ['ordem_apresentacao', 'uf'],
            },
        ),
        migrations.CreateModel(
            name='FundoAnbima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_fundo', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ Fundo')),
                ('nome_fundo', models.CharField(max_length=150, unique=True, verbose_name='Nome do Fundo')),
                ('codigo_anbima', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código ANBIMA')),
                ('ordem_apresentacao', models.IntegerField(default=0, verbose_name='Ordem de Apresentação')),
            ],
            options={
                'verbose_name': 'Fundo (ANBIMA)',
                'verbose_name_plural': 'Valores por Fundos (ANBIMA)',
                'ordering': ['ordem_apresentacao', 'nome_fundo'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_estados_anbima',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_EstadosAnbima'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_fundos_anbima',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_FundosAnbima'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_anbima',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Anbima'),
        ),
    ]
