# Generated by Django 5.1.7 on 2026-03-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_colaborador_agencia_remove_metamensal_agencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidade",
            name="superintendencia",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Superintendência"
            ),
        ),
        migrations.DeleteModel(
            name="Superintendencia",
        ),
    ]
