# Generated by Django 5.1.7 on 2026-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_unidade_superintendencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="verba_credito_folha",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Verba de Repasse para a folha",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="verba_estorno_folha",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Verba de Estorno para a folha",
            ),
        ),
    ]
