# Generated by Django 6.0.7 on 2026-08-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_indicacao_chave_unica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='numero_contrato',
        ),
        migrations.RemoveField(
            model_name='indicacao',
            name='numero_endosso',
        ),
        migrations.RemoveField(
            model_name='indicacao',
            name='seguradora',
        ),
        migrations.RemoveField(
            model_name='indicacao',
            name='tipo_documento',
        ),
    ]
