# Generated by Django 5.1.7 on 2026-04-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_produto_verba_credito_folha_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="inativado",
            new_name="inativo",
        ),
    ]
