# Generated by Django 6.0.6 on 2026-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_anbima_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoanbima',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='cod_grupo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cód. Grupo SUSEP'),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='grupo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Grupo SUSEP'),
        ),
        migrations.CreateModel(
            name='ParametrizacaoOdonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'PJ / PME')], max_length=2)),
                ('campo_sistema', models.CharField(max_length=100)),
                ('coluna_excel', models.CharField(blank=True, max_length=150, null=True)),
                ('valor_fixo', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Parametrização Odonto',
                'verbose_name_plural': 'Parametrizações Odonto',
                'unique_together': {('origem', 'campo_sistema')},
            },
        ),
    ]
