# Generated by Django 6.0.6 on 2026-08-31 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_estadoanbima_uf_alter_ramo_cod_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='chave_unica',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Chave única'),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do contrato/apólice'),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='numero_endosso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do endosso'),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='seguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seguradora', verbose_name='Seguradora'),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodocumento', verbose_name='Tipo de Documento'),
        ),
    ]
