# Generated by Django 5.1.7 on 2026-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_inativado_produto_inativo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agrupamento",
            name="inativado",
        ),
        migrations.AddField(
            model_name="agrupamento",
            name="inativo",
            field=models.BooleanField(default=False, verbose_name="Inativo"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="inativo",
            field=models.BooleanField(default=False, verbose_name="inativo"),
        ),
    ]
