# Generated by Django 6.0.6 on 2026-08-31 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_indicacao_chave_unica_indicacao_numero_contrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilidadeRamoOdonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_planilha', models.CharField(max_length=150, unique=True, verbose_name='Ramo da planilha')),
                ('ramo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ramo', verbose_name='Ramo da base')),
            ],
            options={
                'verbose_name': 'Compatibilidade de Ramo (Odonto)',
                'verbose_name_plural': 'Compatibilidades de Ramo (Odonto)',
            },
        ),
    ]
