# Generated by Django 6.0.6 on 2026-09-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_compatibilidaderamoodonto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproducao',
            name='cliente_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_producao', to='core.cliente', verbose_name='Cliente (cadastro)'),
        ),
        migrations.AlterField(
            model_name='seguradora',
            name='cod_seguradora',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Cód. Seguradora'),
        ),
    ]
