# Generated by Django 5.1.7 on 2026-04-16 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_perfilusuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="aba_base",
            field=models.BooleanField(default=False, verbose_name="Acessar Aba Base"),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="aba_producao",
            field=models.BooleanField(
                default=False, verbose_name="Acessar Aba Produção"
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="sub_base_formularios",
            field=models.BooleanField(
                default=False, verbose_name="↳ Base - Formulários"
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="sub_base_processamentos",
            field=models.BooleanField(
                default=False, verbose_name="↳ Base - Processamentos"
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="sub_base_relatorios",
            field=models.BooleanField(
                default=False, verbose_name="↳ Base - Relatórios"
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="sub_prod_formularios",
            field=models.BooleanField(
                default=False, verbose_name="↳ Produção - Formulários"
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
