# Generated by Django 5.1.7 on 2026-04-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_perfilusuario_aba_base_perfilusuario_aba_producao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="cid_coordenadoria",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="CID Coordenadoria"
            ),
        ),
    ]
