# Generated by Django 6.0.6 on 2026-09-29 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_registroproducao_cliente_cadastro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicacaoRenovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carimbo_data_hora', models.DateTimeField(blank=True, null=True, verbose_name='Carimbo de data/hora')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Endereço de e-mail')),
                ('email_indicador_outro', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do indicador (se não for você)')),
                ('matricula_indicador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula do indicador')),
                ('nome_indicador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome completo do indicador')),
                ('cid_agencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID da agência')),
                ('telefone_indicador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone ou celular do indicador')),
                ('enviar_orcamento_para', models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Indicador', 'Indicador')], max_length=15, null=True, verbose_name='Enviar orçamento para')),
                ('origem_informacao', models.CharField(blank=True, choices=[('WhatsApp', 'WhatsApp'), ('Planilha da internet', 'Planilha da internet'), ('Telefone', 'Telefone'), ('E-mail', 'E-mail')], max_length=30, null=True, verbose_name='Origem da informação')),
                ('nome_cliente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome completo do cliente')),
                ('telefone_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone ou celular do cliente')),
                ('cpf_cliente', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF do cliente')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do cliente')),
                ('produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto')),
                ('dados_veiculo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dados do veículo (modelo, ano e placa)')),
                ('possui_seguro', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cliente já possui seguro?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('numero_contrato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do contrato/apólice')),
                ('numero_endosso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do endosso')),
                ('chave_unica', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Chave única')),
                ('atendimento_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Em atendimento por')),
                ('atendimento_em', models.DateTimeField(blank=True, null=True, verbose_name='Em atendimento desde')),
                ('ramo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ramo', verbose_name='Grupo/Ramo')),
                ('responsavel_demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_responsavel_renovacao', to='core.colaborador', verbose_name='Responsável pela demanda')),
                ('seguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seguradora', verbose_name='Seguradora')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Indicação (Base Renovação)',
                'verbose_name_plural': 'Indicações (Base Renovação)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LigacaoRenovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Protocolo')),
                ('data_ligacao', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da ligação')),
                ('status', models.CharField(blank=True, choices=[('Atendida', 'Atendida'), ('Não atendida', 'Não atendida'), ('Caixa postal', 'Caixa postal'), ('Reagendar', 'Reagendar')], max_length=20, null=True, verbose_name='Status da ligação')),
                ('proximo_contato', models.DateTimeField(blank=True, null=True, verbose_name='Próximo contato')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da ligação')),
                ('ramal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ramal')),
                ('venda_central', models.BooleanField(default=False, verbose_name='Venda Central')),
                ('premio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prêmio Total')),
                ('agn', models.BooleanField(default=False, verbose_name='Agn')),
                ('motivo_nao_venda', models.CharField(blank=True, choices=[('Condições comerciais (preço)', 'Condições comerciais (preço)'), ('Condições financeiras', 'Condições financeiras'), ('Condições técnicas', 'Condições técnicas'), ('Desistiu', 'Desistiu'), ('Efetivou com o corretor atual', 'Efetivou com o corretor atual'), ('Falta de retorno do cliente/indicador', 'Falta de retorno do cliente/indicador'), ('Mal atendimento Seguradora', 'Mal atendimento Seguradora'), ('Operação Empréstimo', 'Operação Empréstimo'), ('Venda do bem', 'Venda do bem')], max_length=50, null=True, verbose_name='Motivo Não Venda')),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão (%)')),
                ('cadastrado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cadastrado/tratado por')),
                ('indicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacoes', to='core.indicacaorenovacao')),
                ('seguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seguradora', verbose_name='Seguradora')),
            ],
            options={
                'verbose_name': 'Ligação (Base Renovação)',
                'verbose_name_plural': 'Ligações (Base Renovação)',
                'ordering': ['-data_ligacao', '-id'],
            },
        ),
    ]
