# Generated by Django 5.1.7 on 2026-04-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_perfilusuario_cid_coordenadoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="ramo",
            name="agrupamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.agrupamento",
                verbose_name="Agrupamento",
            ),
        ),
    ]
