# Generated by Django 6.0.6 on 2026-09-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_indicacaoendosso_ligacaoendosso'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacaoendosso',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='indicacaoendosso',
            name='tipo_endosso',
            field=models.CharField(blank=True, choices=[('Endosso de cancelamento', 'Endosso de cancelamento'), ('Endosso de substituição de item', 'Endosso de substituição de item'), ('Endosso de perfil', 'Endosso de perfil'), ('Endosso de inclusão de item', 'Endosso de inclusão de item'), ('Endosso de alteração de dados cadastrais', 'Endosso de alteração de dados cadastrais'), ('Endosso de alteração de perfil', 'Endosso de alteração de perfil'), ('Outros', 'Outros')], max_length=60, null=True, verbose_name='Endosso'),
        ),
        migrations.AlterField(
            model_name='indicacaoendosso',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice'),
        ),
    ]
