# Generated by Django 5.1.7 on 2026-04-28 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_ramo_agrupamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("IMPORTADOS", "Importados"),
                            ("PENDENTES", "Pendentes"),
                            ("EMITIDOS", "Emitidos"),
                        ],
                        default="IMPORTADOS",
                        max_length=20,
                        verbose_name="Fase do Card",
                    ),
                ),
                (
                    "data_relatorio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Relatório"
                    ),
                ),
                (
                    "mes",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Mês"
                    ),
                ),
                (
                    "data_expedicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Expedição"
                    ),
                ),
                (
                    "ramo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ramo"
                    ),
                ),
                (
                    "agencia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "sr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="SR"
                    ),
                ),
                (
                    "contrato",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Contrato"
                    ),
                ),
                (
                    "cod_operacao",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Cód. Operação",
                    ),
                ),
                (
                    "tipo_negocio",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de Negócio",
                    ),
                ),
                (
                    "segurado",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Segurado"
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="CPF / CNPJ"
                    ),
                ),
                (
                    "situacao_contrato",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Situação do Contrato",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nasc."
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Emissão"
                    ),
                ),
                (
                    "vigencia_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigência Inicial"
                    ),
                ),
                (
                    "vigencia_final",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigência Final"
                    ),
                ),
                (
                    "vlr_seguro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Vlr Seguro",
                    ),
                ),
                (
                    "premio_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Prêmio Total",
                    ),
                ),
                (
                    "vlr_tarifa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Vlr da Tarifa",
                    ),
                ),
                (
                    "num_apolice",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nº da Apólice",
                    ),
                ),
                (
                    "parcela",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Parcela"
                    ),
                ),
                (
                    "cod_mensagem_bvr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Cód. Mensagem BVR",
                    ),
                ),
                (
                    "mensagem_bvr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem BVR"
                    ),
                ),
                (
                    "data_retorno_bvr",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Retorno BVR"
                    ),
                ),
                (
                    "motivo_devolucao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo de Devolução"
                    ),
                ),
                (
                    "criado_por",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Criado Por"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Situação"
                    ),
                ),
                (
                    "data_tratamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Tratamento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "agrupamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registro_prod_fase_set",
                        to="core.agrupamento",
                    ),
                ),
            ],
        ),
    ]
