# Generated by Django 5.1.7 on 2026-04-29 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_registroproducao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroproducao",
            name="agencia",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="cod_mensagem_bvr",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="cod_operacao",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="contrato",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="criado_por",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="data_emissao",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="data_expedicao",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="data_relatorio",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="data_retorno_bvr",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="data_tratamento",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="mensagem_bvr",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="mes",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="motivo_devolucao",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="num_apolice",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="parcela",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="premio_total",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="ramo",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="segurado",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="situacao",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="situacao_contrato",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="sr",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="tipo_negocio",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="vigencia_final",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="vigencia_inicial",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="vlr_seguro",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="vlr_tarifa",
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="celular",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Celular"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="cliente",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Cliente"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="colaborador",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Colaborador"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Cadastrado/importado em",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="documento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Documento"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="email",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="endosso",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Endosso"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="fim_vigencia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fim de vigência"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="gerente_agencia",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Gerente da agência"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="grupo_ramo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Grupo/Ramo"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="inicio_vigencia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Início de vigência"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="mes_producao",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Mês da produção"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="nome_social",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome social"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="perc_comissao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="% de comissão",
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="premio_bruto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Prêmio bruto",
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="qtd_parcelas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade de parcelas"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="realizado",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Realizado"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="seguradora",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Seguradora"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="superintendencia",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Superintendência"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="superintendente",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Superintendente"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="tipo_documento",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tipo documento"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="tipo_pessoa",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Tipo de pessoa"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="unidade",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Unidade"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="usuario_cadastro",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Cadastrado/importado por",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="agrupamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registro_prod_fase_set",
                to="core.agrupamento",
            ),
        ),
    ]
