# Generated by Django 6.0.6 on 2026-10-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_indicacaoendosso_item_indicacaoendosso_tipo_endosso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='cliente_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes_novo', to='core.cliente', verbose_name='Cliente (cadastro)'),
        ),
        migrations.AddField(
            model_name='indicacaorenovacao',
            name='cliente_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes_renovacao', to='core.cliente', verbose_name='Cliente (cadastro)'),
        ),
        migrations.AddField(
            model_name='indicacaoendosso',
            name='cliente_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes_endosso', to='core.cliente', verbose_name='Cliente (cadastro)'),
        ),
    ]
