# Generated by Django 5.1.7 on 2026-05-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_registroproducao_agencia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ramo",
            name="agrupamento",
        ),
        migrations.AlterField(
            model_name="ramo",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.produto",
                verbose_name="Produto",
            ),
        ),
    ]
