# Generated by Django 6.0.6 on 2026-10-05 10:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_indicacao_cliente_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_vendas_baseemissao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Vendas_BaseEmissao'),
        ),
        migrations.CreateModel(
            name='AcompanhamentoEmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('novo', 'Novo'), ('renovacao', 'Renovação'), ('endosso', 'Endosso')], max_length=10, verbose_name='Origem')),
                ('registro_id', models.PositiveIntegerField(verbose_name='ID do registro (na tabela da origem)')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do registro')),
                ('atendente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Atendente')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('Aguardando emissão', 'Aguardando emissão'), ('Pendência', 'Pendência'), ('Recusada', 'Recusada'), ('Emitida', 'Emitida')], default='Aguardando emissão', max_length=20, verbose_name='Status')),
                ('apolice_enviada', models.BooleanField(default=False, verbose_name='Apólice enviada ao cliente')),
                ('data_envio_cliente', models.DateField(blank=True, null=True, verbose_name='Data de envio ao cliente')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de emissão')),
                ('numero_apolice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da apólice')),
            ],
            options={
                'verbose_name': 'Acompanhamento de Emissão',
                'verbose_name_plural': 'Acompanhamentos de Emissão',
                'ordering': ['-data_registro', '-id'],
                'indexes': [models.Index(fields=['origem', 'registro_id'], name='core_acompa_origem_80d793_idx')],
            },
        ),
    ]
