# Generated by Django 6.0.6 on 2026-10-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_acompanhamento_emissao_e_baseemissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='tipo_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopessoa', verbose_name='Tipo de Pessoa'),
        ),
        migrations.AddField(
            model_name='indicacaorenovacao',
            name='tipo_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopessoa', verbose_name='Tipo de Pessoa'),
        ),
        migrations.AddField(
            model_name='indicacaoendosso',
            name='tipo_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopessoa', verbose_name='Tipo de Pessoa'),
        ),
    ]
