# Generated by Django 5.1.7 on 2026-05-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_remove_ramo_agrupamento_alter_ramo_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="cod_ppo_rateio",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="cod_ppo_volume",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="verba_credito_folha",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="verba_estorno_folha",
        ),
        migrations.AddField(
            model_name="ramo",
            name="cod_ppo_rateio",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Cód. PPO Rat."
            ),
        ),
        migrations.AddField(
            model_name="ramo",
            name="cod_ppo_volume",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Cód. PPO Vol."
            ),
        ),
        migrations.AddField(
            model_name="ramo",
            name="verba_estorno_folha",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Verba Estorno"
            ),
        ),
        migrations.AddField(
            model_name="ramo",
            name="verba_repasse_folha",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Verba Repasse"
            ),
        ),
    ]
