# Generated by Django 5.1.7 on 2026-05-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_produto_cod_ppo_rateio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroproducao",
            name="grupo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Grupo"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="motivo_endosso",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Motivo do endosso"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="premio_liquido",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Prêmio líquido",
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="renovacao_propria",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Renovação própria"
            ),
        ),
        migrations.CreateModel(
            name="EndossoAdicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes_producao",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Mês da produção",
                    ),
                ),
                (
                    "endosso",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Endosso"
                    ),
                ),
                (
                    "motivo_endosso",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Motivo do endosso",
                    ),
                ),
                (
                    "inicio_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Início de vigência"
                    ),
                ),
                (
                    "fim_vigencia",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim de vigência"
                    ),
                ),
                (
                    "qtd_parcelas",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Quantidade de parcelas"
                    ),
                ),
                (
                    "renovacao_propria",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Renovação própria",
                    ),
                ),
                (
                    "premio_bruto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Prêmio bruto",
                    ),
                ),
                (
                    "premio_liquido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Prêmio líquido",
                    ),
                ),
                (
                    "perc_comissao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% de comissão",
                    ),
                ),
                (
                    "realizado",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Realizado"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Unidade"
                    ),
                ),
                (
                    "superintendencia",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Superintendência",
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Grupo"
                    ),
                ),
                (
                    "colaborador",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Colaborador",
                    ),
                ),
                (
                    "gerente_agencia",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Gerente da agência",
                    ),
                ),
                (
                    "superintendente",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Superintendente",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Adicionado em"
                    ),
                ),
                (
                    "registro_pai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endossos_extras",
                        to="core.registroproducao",
                    ),
                ),
            ],
        ),
    ]
