# Generated by Django 5.1.7 on 2026-06-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_registroproducao_grupo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompatibilidadeSeguradora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_planilha", models.CharField(max_length=150, unique=True)),
                (
                    "seguradora_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.seguradora",
                    ),
                ),
            ],
        ),
    ]
