# Generated by Django 5.1.7 on 2026-06-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_compatibilidadeseguradora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroproducao",
            name="seguradora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.seguradora",
                verbose_name="Seguradora",
            ),
        ),
    ]
