# Generated by Django 5.1.7 on 2026-06-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_registroproducao_seguradora"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoPessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod_tipo",
                    models.CharField(
                        max_length=1, unique=True, verbose_name="Código (F, J, E)"
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(max_length=50, verbose_name="Tipo de Pessoa"),
                ),
                (
                    "observacoes",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Observações",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="produto",
            name="mes_producao_em_aberto",
            field=models.DateField(
                blank=True, null=True, verbose_name="Mês Production em Aberto"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="celular",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Cellular"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="tipo_pessoa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.tipopessoa",
                verbose_name="Tipo de Pessoa",
            ),
        ),
    ]
