# Generated by Django 5.1.7 on 2026-06-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_tipopessoa_alter_produto_mes_producao_em_aberto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tipopessoa",
            name="cod_tipo",
        ),
    ]
