# Generated by Django 5.1.7 on 2026-06-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_tipopessoa_cod_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametrizacaoHabitacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo_sistema", models.CharField(max_length=100, unique=True)),
                (
                    "coluna_excel",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("valor_fixo", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
