# Generated by Django 5.1.7 on 2026-06-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_parametrizacaohabitacional"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registroproducao",
            options={
                "verbose_name": "Registro de Produção",
                "verbose_name_plural": "Registros de Produção",
            },
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="data_cadastro",
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="agencia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="contrato",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="segurado",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="vlr_seguro",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="agrupamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.agrupamento",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="celular",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Celular"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="colaborador",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Matrícula do Colaborador",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="cpf_cnpj",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CPF / CNPJ"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="fase",
            field=models.CharField(
                default="IMPORTADOS", max_length=50, verbose_name="Fase"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="gerente_agencia",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Matrícula do Gerente",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="mes_producao",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Mês da produção"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="motivo_endosso",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Motivo do endosso"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="perc_comissao",
            field=models.FloatField(
                blank=True, null=True, verbose_name="% de comissão"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="premio_bruto",
            field=models.FloatField(blank=True, null=True, verbose_name="Prêmio bruto"),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="premio_liquido",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Prêmio Líquido"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="qtd_parcelas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Qtd. parcelas"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="renovacao_propria",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Renovação Própria"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="seguradora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.seguradora",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="superintendente",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Matrícula do Superintendente",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.unidade",
                verbose_name="Unidade (CID)",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="usuario_cadastro",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Usuário Cadastro"
            ),
        ),
    ]
