# Generated by Django 5.1.7 on 2026-06-17 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_registroproducao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroproducao",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 6, 17, 14, 18, 18, 92793, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Adicionado em",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="gerente_agencia",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Gerente da agência"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="superintendente",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Superintendente"
            ),
        ),
    ]
