# Generated by Django 5.1.7 on 2026-06-18 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_registroproducao_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registroproducao",
            options={},
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="agencia",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="contrato",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="gerente_agencia",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="grupo",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="motivo_endosso",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="segurado",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="superintendencia",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="superintendente",
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="vlr_seguro",
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Importado em",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="cliente",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Cliente"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="colaborador",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Colaborador"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="fase",
            field=models.CharField(
                choices=[
                    ("IMPORTADOS", "Importados"),
                    ("VALIDAÇÃO", "Validação"),
                    ("DIVERGENTES", "Divergentes"),
                    ("PRONTO PARA ENVIO", "Pronto para Envio"),
                    ("PRODUÇÃO", "Produção"),
                ],
                default="IMPORTADOS",
                max_length=50,
                verbose_name="Fase",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="grupo_ramo",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Grupo/Ramo"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="nome_social",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome social"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="seguradora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.seguradora",
                verbose_name="Seguradora",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="usuario_cadastro",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Importado por"
            ),
        ),
    ]
