# Generated by Django 5.1.7 on 2026-06-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_registroproducao_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registroproducao",
            options={
                "verbose_name": "Registro de Produção",
                "verbose_name_plural": "Registros de Produção",
            },
        ),
        migrations.RemoveField(
            model_name="registroproducao",
            name="data_cadastro",
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="agencia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="contrato",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="gerente_agencia",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Matrícula do Gerente",
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="grupo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Grupo"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="motivo_endosso",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Motivo do endosso"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="segurado",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="superintendencia",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Superintendência"
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="superintendente",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Matrícula do Superintendente",
            ),
        ),
        migrations.AddField(
            model_name="registroproducao",
            name="vlr_seguro",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="cliente",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Cliente"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="colaborador",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Matrícula do Colaborador",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="fase",
            field=models.CharField(
                default="IMPORTADOS", max_length=50, verbose_name="Fase"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="grupo_ramo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Grupo/Ramo"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="nome_social",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome social"
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="seguradora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.seguradora",
            ),
        ),
        migrations.AlterField(
            model_name="registroproducao",
            name="usuario_cadastro",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Usuário Cadastro"
            ),
        ),
    ]
