# Generated by Django 6.0.6 on 2026-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_registroproducao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endossoadicional',
            name='nome_colaborador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Colaborador'),
        ),
        migrations.AddField(
            model_name='endossoadicional',
            name='nome_unidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Unidade'),
        ),
        migrations.AddField(
            model_name='registroproducao',
            name='nome_colaborador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Colaborador'),
        ),
        migrations.AddField(
            model_name='registroproducao',
            name='nome_unidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Unidade'),
        ),
    ]
