# Generated by Django 6.0.6 on 2026-07-03 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_endossoadicional_nome_colaborador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='data_fim_emprego',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fim no Emprego'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_inicio_emprego',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início no Emprego'),
        ),
        migrations.CreateModel(
            name='AuditoriaExportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeriasEstagiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_ferias', models.DateField(verbose_name='Início das Férias')),
                ('quantidade_dias', models.IntegerField(verbose_name='Quantidade de Dias')),
                ('fim_ferias', models.DateField(blank=True, null=True, verbose_name='Fim das Férias')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_ferias', to='core.colaborador', verbose_name='Estagiário')),
            ],
        ),
    ]
