# Generated by Django 6.0.6 on 2026-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_registroproducao_chave_unica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoriaexportacao',
            old_name='nome_arquivo',
            new_name='detalhe',
        ),
        migrations.AddField(
            model_name='auditoriaexportacao',
            name='acao',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
