# Generated by Django 6.0.6 on 2026-07-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_nome_arquivo_auditoriaexportacao_detalhe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carimbo_data_hora', models.DateTimeField(blank=True, null=True, verbose_name='Carimbo de data/hora')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Endereço de e-mail')),
                ('email_indicador_outro', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do indicador (se não for você)')),
                ('matricula_indicador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula do indicador')),
                ('nome_indicador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome completo do indicador')),
                ('cid_agencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID da agência')),
                ('telefone_indicador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone ou celular do indicador')),
                ('enviar_orcamento_para', models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Indicador', 'Indicador')], max_length=15, null=True, verbose_name='Enviar orçamento para')),
                ('nome_cliente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome completo do cliente')),
                ('telefone_cliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone ou celular do cliente')),
                ('cpf_cliente', models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF do cliente')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do cliente')),
                ('produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto')),
                ('dados_veiculo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dados do veículo (modelo, ano e placa)')),
                ('possui_seguro', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cliente já possui seguro?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Indicação (Base Novo)',
                'verbose_name_plural': 'Indicações (Base Novo)',
                'ordering': ['-id'],
            },
        ),
    ]
