# Generated by Django 6.0.6 on 2026-07-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_indicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigacaoIndicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ligacao', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da ligação')),
                ('status', models.CharField(blank=True, choices=[('Atendida', 'Atendida'), ('Não atendida', 'Não atendida'), ('Caixa postal', 'Caixa postal'), ('Reagendar', 'Reagendar')], max_length=20, null=True, verbose_name='Status da ligação')),
                ('proximo_contato', models.DateField(blank=True, null=True, verbose_name='Próximo contato')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da ligação')),
                ('indicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacoes', to='core.indicacao')),
            ],
            options={
                'verbose_name': 'Ligação (Base Novo)',
                'verbose_name_plural': 'Ligações (Base Novo)',
                'ordering': ['-data_ligacao', '-id'],
            },
        ),
    ]
