# Generated by Django 6.0.6 on 2026-07-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_indicacao_chave_unica_indicacao_numero_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='protocolo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Protocolo'),
        ),
    ]
