# Generated by Django 6.0.6 on 2026-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_ligacaoindicacao_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='agn',
            field=models.BooleanField(default=False, verbose_name='Agn'),
        ),
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='cadastrado_por',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cadastrado/tratado por'),
        ),
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='dt_hr_religacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt/Hr religação'),
        ),
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='motivo_nao_venda',
            field=models.CharField(blank=True, choices=[('Preco_alto', 'Preço alto'), ('Ja_possui_seguro', 'Cliente já possui seguro'), ('Sem_interesse', 'Sem interesse'), ('Sem_contato', 'Não conseguiu contato')], max_length=30, null=True, verbose_name='Motivo Não Venda'),
        ),
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='ramal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ramal'),
        ),
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='venda_central',
            field=models.BooleanField(default=False, verbose_name='Venda Central'),
        ),
    ]
