# Generated by Django 6.0.6 on 2026-07-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_ligacaoindicacao_agn_ligacaoindicacao_cadastrado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoNaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100, null=True, unique=True, verbose_name='Motivo Não Venda')),
            ],
            options={
                'verbose_name': 'Motivo Não Venda',
                'verbose_name_plural': 'Motivos Não Venda',
                'ordering': ['motivo'],
            },
        ),
        migrations.AlterField(
            model_name='ligacaoindicacao',
            name='motivo_nao_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.motivonaovenda', verbose_name='Motivo Não Venda'),
        ),
    ]
