# Generated by Django 6.0.6 on 2026-07-17 16:18

from django.db import migrations, models


def normalizar_proximo_contato(apps, schema_editor):
    # registos antigos guardaram só a data (YYYY-MM-DD, 10 caracteres); ao virar
    # DateTimeField isso precisa de um horário junto ou o parser do SQLite falha ao ler.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE core_ligacaoindicacao SET proximo_contato = proximo_contato || ' 00:00:00' "
            "WHERE proximo_contato IS NOT NULL AND length(proximo_contato) = 10"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_seed_motivo_nao_venda'),
    ]

    operations = [
        migrations.RunPython(normalizar_proximo_contato, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ligacaoindicacao',
            name='dt_hr_religacao',
        ),
        migrations.AlterField(
            model_name='ligacaoindicacao',
            name='proximo_contato',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próximo contato'),
        ),
    ]
