# Generated by Django 6.0.6 on 2026-07-17 16:35

from django.db import migrations, models


def seed_sequencias_protocolo(apps, schema_editor):
    # inicializa o contador com o maior número já usado em cada prefixo (ano+mês),
    # pra sequência atômica nova continuar dali em vez de repetir protocolos existentes
    LigacaoIndicacao = apps.get_model('core', 'LigacaoIndicacao')
    SequenciaProtocolo = apps.get_model('core', 'SequenciaProtocolo')

    maximos = {}
    protocolos = LigacaoIndicacao.objects.exclude(protocolo__isnull=True).exclude(protocolo='').values_list('protocolo', flat=True)
    for protocolo in protocolos:
        prefixo, resto = protocolo[:6], protocolo[6:]
        if len(prefixo) == 6 and prefixo.isdigit() and resto.isdigit():
            maximos[prefixo] = max(maximos.get(prefixo, 0), int(resto))

    for prefixo, numero in maximos.items():
        SequenciaProtocolo.objects.update_or_create(prefixo=prefixo, defaults={'ultimo_numero': numero})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_ligacaoindicacao_dt_hr_religacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=6, unique=True, verbose_name='Prefixo (ano+mês)')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, verbose_name='Último número usado')),
            ],
            options={
                'verbose_name': 'Sequência de Protocolo',
                'verbose_name_plural': 'Sequências de Protocolo',
            },
        ),
        migrations.RunPython(seed_sequencias_protocolo, migrations.RunPython.noop),
    ]
