# Generated by Django 6.0.6 on 2026-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_sequenciaprotocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligacaoindicacao',
            name='premio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prêmio Total'),
        ),
    ]
