# Generated by Django 6.0.6 on 2026-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_ligacaoindicacao_premio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='origem_informacao',
            field=models.CharField(blank=True, choices=[('WhatsApp', 'WhatsApp'), ('Planilha da internet', 'Planilha da internet'), ('Telefone', 'Telefone')], max_length=30, null=True, verbose_name='Origem da informação'),
        ),
    ]
