# Generated by Django 6.0.6 on 2026-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_indicacao_origem_informacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicacaoExcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carimbo_data_hora', models.DateTimeField(verbose_name='Carimbo de data/hora')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Endereço de e-mail')),
                ('excluido_em', models.DateTimeField(auto_now_add=True, verbose_name='Excluído em')),
                ('excluido_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Excluído por')),
            ],
            options={
                'verbose_name': 'Indicação Excluída',
                'verbose_name_plural': 'Indicações Excluídas',
                'unique_together': {('carimbo_data_hora', 'email')},
            },
        ),
    ]
