# Generated by Django 6.0.6 on 2026-07-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_indicacaoexcluida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='aba_base',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='aba_producao',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='aba_auditoria',
            field=models.BooleanField(default=False, verbose_name='Acessar Aba Auditoria'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_vinculados', to='core.colaborador'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sub_admin_criar',
            field=models.BooleanField(default=False, verbose_name='↳ Administração - Criar Usuários'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sub_admin_estagiarios',
            field=models.BooleanField(default=False, verbose_name='↳ Administração - Gestão Estagiários'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sub_fin_extratos',
            field=models.BooleanField(default=False, verbose_name='↳ Financeiro - Extratos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sub_fin_formularios',
            field=models.BooleanField(default=False, verbose_name='↳ Financeiro - Formulários'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sub_fin_relatorios',
            field=models.BooleanField(default=False, verbose_name='↳ Financeiro - Relatórios'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sub_prod_processamentos',
            field=models.BooleanField(default=False, verbose_name='↳ Produção - Processamentos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sub_prod_relatorios',
            field=models.BooleanField(default=False, verbose_name='↳ Produção - Relatórios'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sub_prod_vendas',
            field=models.BooleanField(default=False, verbose_name='↳ Produção - Vendas'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('COMUM', 'Leitor'), ('ADMIN', 'Editor'), ('MASTER', 'Proprietário')], default='COMUM', max_length=10),
        ),
    ]
