# Generated by Django 6.0.6 on 2026-07-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_perfilusuario_aba_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceiroHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_colaborador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Matrícula do Colaborador')),
                ('data_processamento', models.CharField(blank=True, max_length=7, null=True, verbose_name='Mês/Ano de Processamento')),
                ('valor', models.DecimalField(decimal_places=2, default=100.0, max_digits=15, verbose_name='Valor')),
            ],
        ),
        migrations.AlterField(
            model_name='endossoadicional',
            name='endosso',
            field=models.CharField(blank=True, default=0, max_length=8, verbose_name='Endosso'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='endossoadicional',
            constraint=models.UniqueConstraint(fields=('registro_pai', 'endosso'), name='unique_registro_pai_endosso'),
        ),
        migrations.AddField(
            model_name='financeirohabitacional',
            name='registro_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro_habitacional', to='core.registroproducao', verbose_name='Registro de Produção (Endosso)'),
        ),
    ]
