# Generated by Django 5.2.5 on 2026-07-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_financeirohabitacional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_fin_extratos',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sub_fin_processamentos',
            field=models.BooleanField(default=False, verbose_name='↳ Financeiro - Processamentos'),
        ),
    ]
