# Generated by Django 5.1.7 on 2026-08-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_remove_perfilusuario_sub_fin_extratos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicacao",
            name="atendimento_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Em atendimento desde"
            ),
        ),
        migrations.AddField(
            model_name="indicacao",
            name="atendimento_por",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Em atendimento por"
            ),
        ),
    ]
