# Generated by Django 5.1.7 on 2026-08-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_indicacao_atendimento_em_indicacao_atendimento_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="ligacaoindicacao",
            name="seguradora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.seguradora",
                verbose_name="Seguradora",
            ),
        ),
    ]
