# Generated by Django 5.1.7 on 2026-08-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_ligacaoindicacao_seguradora"),
    ]

    operations = [
        migrations.AddField(
            model_name="ligacaoindicacao",
            name="comissao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Comissão (%)",
            ),
        ),
    ]
