# Generated by Django 6.0.6 on 2026-08-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_ligacaoindicacao_comissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrizacaoBaseNovo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_sistema', models.CharField(max_length=100, unique=True)),
                ('coluna_excel', models.CharField(blank=True, max_length=150, null=True)),
                ('valor_fixo', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
