# Generated by Django 6.0.6 on 2026-08-10 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_ligacaoindicacao_comissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='aba_auditoria',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nivel_acesso',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_admin_criar',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_admin_estagiarios',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_base_formularios',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_base_processamentos',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_base_relatorios',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_fin_formularios',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_fin_processamentos',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_fin_relatorios',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_prod_formularios',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_prod_processamentos',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_prod_relatorios',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='sub_prod_vendas',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='admin_feriasestagiarios',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Admin_FeriasEstagiarios'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='admin_listaestagiarios',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Admin_ListaEstagiarios'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='admin_usuario',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Admin_Usuario'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='aud',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Aud'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_agrupamentos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_Agrupamentos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_clientes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_Clientes'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_colaboradores',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_Colaboradores'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_contratados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_Contratados'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_metas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_Metas'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_produtos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_Produtos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_ramos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_Ramos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_seguradoras',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_Seguradoras'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_tipopessoa',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_TipoPessoa'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_tiposdocumento',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_TiposDocumento'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_form_unidade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Form_Unidade'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_proc_colaboradores',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Proc_Colaboradores'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_proc_ramos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Proc_Ramos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_proc_unidade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Proc_Unidade'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='base_rel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Base_Rel'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fin_form',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Fin_Form'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fin_proc_habitacional',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Fin_Proc_Habitacional'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fin_rel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Fin_Rel'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_banescap',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_Banescap'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_bap',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_BAP'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_consorcio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_Consorcio'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_habitacional',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_Habitacional'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_odonto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_Odonto'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_patrimonialedemais',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_PatrimonialEDemais'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_prestamista',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_Prestamista'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_previdencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_Previdencia'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_saude',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_Saude'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_form_vida',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Form_Vida'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_banescap',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Banescap'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_bap',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_BAP'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_basenovo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Basenovo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_consorcio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Consorcio'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_habitacional',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Habitacional'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_odonto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Odonto'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_patrimonialedemais',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_PatrimonialEDemais'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_prestamista',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Prestamista'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_previdencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Previdencia'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_saude',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Saude'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_proc_vida',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Proc_Vida'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_rel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Rel'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_vendas_baseendosso',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Vendas_BaseEndosso'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_vendas_basenovo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Vendas_BaseNovo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_vendas_baserenovacao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Vendas_BaseRenovacao'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_vendas_endosso',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Vendas_Endosso'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_vendas_novo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Vendas_Novo'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_vendas_renovacao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Vendas_Renovacao'),
        ),
        migrations.AlterField(
            model_name='endossoadicional',
            name='renovacao_propria',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Renovação Própria'),
        ),
        migrations.AlterField(
            model_name='registroproducao',
            name='endosso',
            field=models.CharField(blank=True, default=0, max_length=8, verbose_name='Endosso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroproducao',
            name='renovacao_propria',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Renovação Própria'),
        ),
    ]
