# Generated by Django 5.1.7 on 2026-08-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_parametrizacaobasenovo"),
        ("core", "0053_remove_perfilusuario_aba_auditoria_and_more"),
    ]

    operations = []
