# Generated by Django 6.0.6 on 2026-08-12 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_seed_parametrizacaobasenovo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='prod_vendas_emissao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Prod_Vendas_Emissao'),
        ),
    ]
