# Generated by Django 6.0.6 on 2026-08-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_perfilusuario_prod_vendas_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacao',
            name='origem_informacao',
            field=models.CharField(blank=True, choices=[('WhatsApp', 'WhatsApp'), ('Planilha da internet', 'Planilha da internet'), ('Telefone', 'Telefone'), ('E-mail', 'E-mail')], max_length=30, null=True, verbose_name='Origem da informação'),
        ),
    ]
